# -*- coding: utf-8 -*-
"""The Apex Insurance logo. THE single source of truth for the brand mark.

"Summit" (chosen September 2026): the A as a mountain peak in two facets with
a sunlit cap. Apex means the highest point, so the mark says the name.

Everything that shows the logo is generated from this file:
    chrome.header()   -> lockup("full")        header and mobile drawer
    chrome.footer()   -> lockup("reversed")    on the navy footer
    build.py          -> favicon_svg()         written to assets/favicon.svg

To change the logo, change GEOMETRY or WORDMARK here and run a full build.
Never hand-edit assets/favicon.svg, and never paste the polygons anywhere else.

Rules of use (design-system/MASTER.md, "Logo"):
  * The amber cap is part of the mark, not decoration. It is the one place
    amber appears outside the CTA, and the mark must never ship without it
    except in the one colour version.
  * Clear space on every side is at least the height of the cap.
  * Never below 16px. Never stretched, outlined, or set on a photograph
    without the reversed palette on a navy ground.
"""

# The mark, on a 64 x 64 grid. (role, polygon points). Roles map to a palette.
GEOMETRY = [
    ("left",  "24.73,19.5 32,19.5 32,34 20,58 4,58"),    # left facet of the peak
    ("right", "32,19.5 39.27,19.5 60,58 44,58 32,34"),   # right facet
    ("cap",   "32,6 26.2,16.8 37.8,16.8"),               # the sunlit summit
]

# Inline palettes use the design tokens, so the logo follows src/input.css.
# The favicon is a standalone file and cannot read them, so HEX mirrors the
# three token values; tools/check.py fails if they ever drift apart.
PALETTES = {
    "full":     {"left": "var(--color-navy)", "right": "var(--color-navy-700)", "cap": "var(--color-gold)"},
    "reversed": {"left": "#FFFFFF",           "right": "#BBD3FA",               "cap": "var(--color-gold)"},
    "mono":     {"left": "currentColor",      "right": "currentColor",          "cap": "currentColor"},
}
HEX = {"--color-navy": "#0B3B8C", "--color-navy-700": "#1E6AE1", "--color-gold": "#F5A623"}

WORDMARK = ("Apex", "Insurance")     # the display line, and the tracked line under it
NAME = "Apex Insurance"              # what assistive tech hears


def _shapes(palette):
    return "".join('<polygon points="%s" fill="%s"/>' % (pts, palette[role]) for role, pts in GEOMETRY)


def mark(size=36, palette="full", cls=""):
    """The mark alone, inline. Decorative here: the lockup's link carries the name."""
    c = (' class="%s"' % cls) if cls else ""
    return ('<svg%s width="%d" height="%d" viewBox="0 0 64 64" aria-hidden="true" focusable="false">%s</svg>'
            % (c, size, size, _shapes(PALETTES[palette])))


def lockup(palette="full", size=36):
    """Mark plus wordmark. The caller wraps it in the home link where needed."""
    return ('<span class="logo">%s<span class="logo-word"><span class="wordmark">%s</span>'
            '<span class="wordmark-sub">%s</span></span></span>'
            % (mark(size, palette, "logo-mark"), WORDMARK[0], WORDMARK[1]))


def favicon_svg():
    """Reversed mark on a navy rounded square: a bare navy mark disappears on a
    dark browser tab. Scaled to 72% so the peak keeps its clear space."""
    shapes = _shapes({"left": "#FFFFFF", "right": "#BBD3FA", "cap": HEX["--color-gold"]})
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">\n'
            '  <!-- Generated by tools/logo.py. Do not edit: run python3 tools/build.py -->\n'
            '  <rect width="64" height="64" rx="14" fill="%s"/>\n'
            '  <g transform="translate(9 9.5) scale(0.72)">%s</g>\n'
            '</svg>\n' % (HEX["--color-navy"], shapes))
